# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'oceancare'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Contribute', folder: 'pages', file: 'contribute'}
- {name: 'Free Porter Services', folder: 'pages', file: 'porter_services'}
- {name: 'Plasma Donors Directory', folder: 'pages', file: 'plasma_donors'}
- {name: 'Inspiration', folder: 'pages', file: 'inspiration'}
- {name: 'Team', folder: 'pages', file: 'team'}
- {name: 'News & Updates', folder: 'pages', file: 'news_updates'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: ''

post_date_prefix: ''

donate_link: 'https://www.ketto.org/fundraiser/ocean-care-covid-relief-in-memories-of-rishi-pathak?utm_medium=oceancare_web&utm_content=406de4737d9a358c0ed5b9af34880cb8&shby=1&utm_source=internal&utm_campaign=ocean-care-covid-relief-in-memories-of-rishi-pathak'

plasma_donor_link: 'https://forms.gle/eZPp5QQBii4a5xtF8'
plasma_donor_directory_link: 'https://docs.google.com/spreadsheets/d/19soXlnLKwZrSdNDZmcGgEY-3TL5Oq7bfg413wNRvkqo/edit?usp=sharing'
porter_service_link: 'https://forms.gle/4EJpGLeo8bUFmDgbA'
porter_service_directory_link: 'https://docs.google.com/spreadsheets/d/1DqaB2M-FMOMFp9FmkosXxJsV4bogO5ksUmJPXTxPP6U/edit?usp=sharing'
porter_service_customer_care_link: tel:+919711679861
porter_service_customer_care_link: +919711679861
